######################################################################
# Automatically generated by qmake (3.0) ?? 11? 27 21:38:16 2018
######################################################################

TEMPLATE = app
TARGET = Qt_helloWorld
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
